### ISSUE TITLE
I can set master properties

### ISSUE THREAD

**Issue by mburke84** [philippfromme/camunda-hackdays-generative-music#13]
- tempo
- volume

**Comment by pedesen** [comment]
Resolved with https://github.com/philippfromme/camunda-hackdays-generative-music/commit/0ef002929e28f917a3dd4b5cb1e8fdf4c701c2b8 and https://github.com/philippfromme/camunda-hackdays-generative-music/commit/40863bcba68f03b769e8ac75b8d9a9d3a839bfaa
